// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHS3JVK0uCQ3e4pCxEDI3IBJhrEpbXChA',
    appId: '1:771750695687:web:25355bebdb757c2211eba2',
    messagingSenderId: '771750695687',
    projectId: 'e-commerce-app-2579a',
    authDomain: 'e-commerce-app-2579a.firebaseapp.com',
    storageBucket: 'e-commerce-app-2579a.appspot.com',
    measurementId: 'G-7GG36Z9NN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fF_l_ir5Bs4WPWyybE5uz4q_6N_L1DU',
    appId: '1:771750695687:android:cd2f931d5239473c11eba2',
    messagingSenderId: '771750695687',
    projectId: 'e-commerce-app-2579a',
    storageBucket: 'e-commerce-app-2579a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0mVUGQuakLA28q3l0QPlIL5xNv-OTrdk',
    appId: '1:771750695687:ios:5a34f6d04081f7e211eba2',
    messagingSenderId: '771750695687',
    projectId: 'e-commerce-app-2579a',
    storageBucket: 'e-commerce-app-2579a.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0mVUGQuakLA28q3l0QPlIL5xNv-OTrdk',
    appId: '1:771750695687:ios:cec32c38b892416b11eba2',
    messagingSenderId: '771750695687',
    projectId: 'e-commerce-app-2579a',
    storageBucket: 'e-commerce-app-2579a.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp.RunnerTests',
  );
}
